[package]
name = "cpu6502"
version = "0.1.2"
edition = "2024"

[dependencies]
phf = { version = "0.13.1", features = ["macros"] }
ringbuffer = "0.15.0"
strum = { version = "0.27.2", features = ["derive"] }

[[test]]
name = "to_lower_test"
path = "tests/to_lower_test.rs"
